language: bash
env:
  matrix:
  - DIST=stretch HW_PLATFORM=bone
  - DIST=stretch HW_PLATFORM=ev3
  - DIST=stretch HW_PLATFORM=rpi
  - DIST=stretch HW_PLATFORM=rpi2
  - DIST=buster HW_PLATFORM=ev3
  - DIST=buster HW_PLATFORM=rpi
  - DIST=buster HW_PLATFORM=rpi2
  - DIST=bullseye HW_PLATFORM=ev3
  global:
  - secure: TQ0+345ltbgvkuRWl1ZNrPE8P2C+0Eppvqd3yqAtfBzCHrZIrIrZcZ8P+WvM3odvrEFrtx2Y8svAAZEO3F7l/h5bP3gmfFnxJJbefz7ml8S8Hs2QV/eUtUKXURCJhvlsIFacYu7WWSzHTYALJmBX+U47CDESKMgwjzBAK32bJukDx4cQ1w9YgyMs72UQUkEOKpkSUEieFoe1nfgLJG53wt0EMQcfOU5o+RcnG1q02eUtpZW7XWq7G8oFN+MLBQ2T8jBZZz0Rl/KGR4yTnb/oVo455O1FII04uCwlWZ1EiwPVWrqg8gOAJ7iQEoBF6dgH9kIvSlQuYo1nuIDW46tz8cAkJ6/Ha60NU/ZSMCmwK+dFQjpGyseYE6xwwP84Z00bqVGP46UohbIIHo8Y9SNYotlGkpYKVKRfQuXHch9p3OVMR0HahKQwfDTWJC8R1XTq4paMGU+j6eQuT861VyNOzvYy/3WPOkeGDFstLDCIQqLWNUC9CTWRSrBgXUe5J4bToWcEIdw4i8n1u/5mPeqfnlv2bHj7mwp14aDpQGztRhx8V9RBfsjuffOGzwY4urI7C2ifyKKSID1IwX9DB7FujQ8WMhYreLkNZBqdeFVWLx3mFyHcfGCCyiSUlBnt+L25UqdtDob+k2f5sTC4q4sps40mLr7lOvAhBzWOjx5eVjQ=
  - secure: XGO/Pak1wTXgC4hzmsJ4QbAxJkJdF5lshjEh6fzx364KPFzLbTIH1pH/mWdyS1TISWKV3rpH6REU8GWYlwO52Nz+0fMDiUvC7OOIia4A3gt7UNSedfmnv7WUNK5rnEXr0AiiroVY+0DGxxP5PSJf/ld2ixP6zCZtflhhmqLmFHwhpOsnCC2GfZPf/Q3PesR+B6G3WahtYeskOOBIjlBIKchR5y8RvuvncnxBZLSSMyXAMLdTzDsiZiFPG2q0m2Thphze6K7oJ5AcheUQMnXLMtE3vqqC/6r9BobQ9/W02zIoqXEIIB1A2czLswPXP499tBdy1WoWqNR3NqBbm7N4YYhevJVvb1acJRUwBUWSjOiWMT0X5Y/IoChp4uOtKiZp+9G3KpuHveRzHa2Uw6tiDDxhicVjaNWAAUBvX3aztfLPk1gGc331E2HUomwtIkNN6IwzO0YB045nTBZSOFfttU7t48+lKAntPF1AS6mUO0XzhfPGbAu1l84sQXlDpesthm5Sc7wyDzMPZiXa/aX05iFxDH1o6/FdieaUngMAU6kUSKl4cb6SagKCYAgFTtGbjMM0XRBv0lFzc1xX/iV5PxBhcfCsGQBKKFFBlhGEGaA19xd+x5ekPoaCQzXn9i8ZyDR4F84Xxmuhv9cuNunJwmGHMuFuDEPueu3lurSWEwk=
sudo: required
dist: xenial
services: docker
install:
- sudo apt-get update
- sudo apt-get install --yes qemu-user-static
before_script:
- docker --version
script:
- docker build
  -t ev3dev/ev3dev-$DIST-$HW_PLATFORM-base
  -f ev3dev-$DIST/$HW_PLATFORM-base.dockerfile
  ev3dev-$DIST
- docker build
  --build-arg BRICKSTRAP_IMAGE_NAME=ev3dev-$DIST-$HW_PLATFORM-generic-$TRAVIS_TAG
  -t ev3dev/ev3dev-$DIST-$HW_PLATFORM-generic
  -f ev3dev-$DIST/$HW_PLATFORM-generic.dockerfile
  ev3dev-$DIST
after_success:
- if [ -n "$TRAVIS_TAG" ]; then
    docker login -u $USER -p $PASSWORD;
    docker push ev3dev/ev3dev-$DIST-$HW_PLATFORM-base;
    docker tag ev3dev/ev3dev-$DIST-$HW_PLATFORM-base ev3dev/ev3dev-$DIST-$HW_PLATFORM-base:$TRAVIS_TAG;
    docker push ev3dev/ev3dev-$DIST-$HW_PLATFORM-base:$TRAVIS_TAG;
    docker push ev3dev/ev3dev-$DIST-$HW_PLATFORM-generic;
    docker tag ev3dev/ev3dev-$DIST-$HW_PLATFORM-generic ev3dev/ev3dev-$DIST-$HW_PLATFORM-generic:$TRAVIS_TAG;
    docker push ev3dev/ev3dev-$DIST-$HW_PLATFORM-generic:$TRAVIS_TAG;
  fi
